{
  "name": "Initiative Bard",
  "version": "1.0.0",
  "manifest_version": 1,
  "action": {
    "title": "Initiative Bard",
    "icon": "/icon.svg",
    "popover": "/",
    "height": 500,
    "width": 300
  }
}
